In [71]:
import pandas as pd
import numpy as np

In [72]:
df=pd.read_csv(r"C:\Users\risla\OneDrive\Desktop\adidas_products.csv")
df.head()

,Title,Product_link,Sub_brand,Sale_price,MRP
0,Samba OG Shoes,https://www.adidas.co.in/samba-og-shoes/B75806...,Originals,₹10 999.00,₹10 999.00
1,Samba OG Shoes,https://www.adidas.co.in/samba-og-shoes/B75807...,Originals,₹10 999.00,₹10 999.00
2,Galaxy 7 Running Shoes,https://www.adidas.co.in/galaxy-7-running-shoe...,Men Performance,₹4 409.50,₹6 299.00
3,PURECHILL SLIDES,https://www.adidas.co.in/purechill-slides/KI00...,Men Sportswear,₹6 599.00,₹6 599.00
4,Adizero EVO SL Shoes,https://www.adidas.co.in/adizero-evo-sl-shoes/...,Men Performance,₹15 999.00,₹15 999.00

In [73]:
df.shape

(1607, 5)

In [74]:
df.duplicated().sum()

np.int64(0)

In [75]:
df['Product_link'].duplicated().sum()

np.int64(0)

In [76]:
df["Sale_price"] = df["Sale_price"].str.replace("₹", "").str.replace(" ", "").str.replace(",", "").astype(float)

In [77]:
df["MRP"]=df["MRP"].str.replace("₹","").str.replace(" ", "").str.replace(",", "").astype(float)

In [78]:
df["Discount_Amount"]=df["MRP"]-df['Sale_price']

In [85]:
df["Discount_pct"]=((df["Discount_Amount"]/df["MRP"])*100).round(2)

In [90]:
df.loc[df['Sale_price']>df['MRP']]

Empty DataFrame
Columns: [Title, Product_link, Sub_brand, Sale_price, MRP, Discount_Amount, Discount_pct]
Index: []

In [89]:
print(f"Rows with Sale Price > MRP: {len(df.loc[df['Sale_price'] > df['MRP']])}")

Rows with Sale Price > MRP: 0

In [92]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1607 entries, 0 to 1606
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Title            1607 non-null   str
 1   Product_link     1607 non-null   str
 2   Sub_brand        1607 non-null   str
 3   Sale_price       1607 non-null   float64
 4   MRP              1607 non-null   float64
 5   Discount_Amount  1607 non-null   float64
 6   Discount_pct     1607 non-null   float64
dtypes: float64(4), str(3)
memory usage: 88.0 KB

In [93]:
df.isnull().sum()

Title              0
Product_link       0
Sub_brand          0
Sale_price         0
MRP                0
Discount_Amount    0
Discount_pct       0
dtype: int64

In [94]:
df

,Title,Product_link,Sub_brand,Sale_price,MRP,Discount_Amount,Discount_pct
0,Samba OG Shoes,https://www.adidas.co.in/samba-og-shoes/B75806...,Originals,10999.0,10999.0,0.0,0.00
1,Samba OG Shoes,https://www.adidas.co.in/samba-og-shoes/B75807...,Originals,10999.0,10999.0,0.0,0.00
2,Galaxy 7 Running Shoes,https://www.adidas.co.in/galaxy-7-running-shoe...,Men Performance,4409.5,6299.0,1889.5,30.00
3,PURECHILL SLIDES,https://www.adidas.co.in/purechill-slides/KI00...,Men Sportswear,6599.0,6599.0,0.0,0.00
4,Adizero EVO SL Shoes,https://www.adidas.co.in/adizero-evo-sl-shoes/...,Men Performance,15999.0,15999.0,0.0,0.00
...,...,...,...,...,...,...,...
1602,Aero Sprint Spark Shoes,https://www.adidas.co.in/aero-sprint-spark-sho...,Performance,2399.5,4799.0,2399.5,50.00
1603,Spinyy Sneaker,https://www.adidas.co.in/spinyy-sneaker/JK8338...,Men Sportswear,3299.5,6599.0,3299.5,50.00
1604,Aquo Slip On Slides,https://www.adidas.co.in/aquo-slip-on-slides/J...,Sportswear,959.5,1599.0,639.5,39.99
1605,Aero Sprint Spark Shoes,https://www.adidas.co.in/aero-sprint-spark-sho...,Performance,2879.5,4799.0,1919.5,40.00
1606,ENIG RUN 1.0 SHOES,https://www.adidas.co.in/enig-run-1.0-shoes/GA...,Men Performance,2299.5,4599.0,2299.5,50.00

In [110]:
Full_priced=df.loc[df['Discount_Amount']==0]
Offer_Priced=df.loc[df['Discount_Amount']>0]


print(f"Products at full price:{len(Full_priced)}")
print(f"Products on Sale:{len(Offer_Priced)}")

Products at full price:271
Products on Sale:1336

In [111]:
df.to_csv("products_clean.csv",index=False)